runners:
  t3-small-30gb:
    family: ["t3.small"]
    cpu: [2]
    image: ubuntu24-full-x64
    volume: 30gb:gp3:125mbs:3000iops
    spot: false
    retry: "false"
    private: false
  t3-small-16gb:
    family: ["t3.small"]
    cpu: [2]
    image: cobalt
    volume: 16gb:gp3:125mbs:3000iops
    spot: false
    retry: "false"
    private: false

images:
  cobalt:
    platform: linux
    arch: x64
    owner: "395063532779"
    name: "ami-example-OptimalCNC-runs-on-ami-example-cobalt-*"
