name: Check RunsOn installation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: RunsOn environment to check
        required: false
        default: production
        type: string

permissions: {}

jobs:
  smoke:
    runs-on: runs-on=${{ github.run_id }}-${{ github.run_attempt }}/cpu=2/family=t3.nano/env=${{ inputs.environment || 'production' }}/spot=lowest-price
    timeout-minutes: 10
    steps:
      - name: Execute on the registered runner
        run: uname -a
